### ISSUE TITLE
ffmpeg version, requires update?

### ISSUE THREAD

**Issue by beeradmoore** [leye0/XamarinAndroidFFmpeg#1]
Hey,
I just come across wanting to do some video composing in Android. I couldn't find any native methods to do it like iOS and after some googling around I found that ffmpeg can run on Android, and then even more googling I found someone has it running in Xamarin.Android! Awesome job!

Grabbed the source, downloaded it and ran it on my galaxy tab s and it appears to have worked fine. From what I can gather from your source. If I can do the certain video composition I plan on doing (trim main video, append short video at the start and end, add watermark for duration of end result image, fade images in for X seconds at certain parts of the video and fade out) with ffmpeg on a desktop, in theory it should work when I use the command line split up in your 2nd method of processing a video? In theory...

Looking through the output of the app, and it says its using ffmpeg v0.11.1. Is upgrading that to 2.7.2 a difficult task and thats why you have stuck with 0.11.1? (I'll have to see if there are any new features I'd benefit from for what I am doing to see if I'd need to do it).

My only other option I could think of was going to be try render all my things out to OpenGL and then have some way to render that OpenGL out to a video file. So if you had any suggestions at all for other libs that I should look into, that'd be greatly appreciated.

**Comment by leye0** [comment]
Hi! Thanks.

At https://github.com/guardianproject/android-ffmpeg-java you'll find most of what I've ported. The original creator worked on some funky helpers to handle filters and overlay (that are not even compatible with his own version of the ffmpeg). Using ffmpeg for media processing is a good idea to avoid hours of coding. Only drawbacks are: 
1. You can't produce any mpeg stuff without paying royalties. I've started to read about integrating Cisco free version of h.264 to ffmpeg but soon realized that you need to download it as is (already compiled) to have them paying the bill for you, so I eliminated this possibility. You're stuck with mp2 or other encoding formats you don't like 
2. If I remember well my benchmark, there is a significant drop in fps compared to OpenGL. Like 12-15 fps instead of 60 fps. (Which is greater than the 8 fps of MediaMetaDataRetriever when extracting and displaying the video frame by frame.)

For the version, I've made my tests with that 0.11 version, but give a look at these 2.2.3 binaries:
https://github.com/hiteshsondhi88/ffmpeg-android-java

This is far better to do this stuff using MediaCodec, MediaExtractor and OpenGL ES 2.0 (or 3.0).

The better place to start is here: http://bigflake.com/mediacodec/

This page looks crappy, but this is the - very - best informations. Among other things, you can see that you are better to use API 18 or more. You'll get live effects at 60 fps by using the surface to surface approach (port the demo or get my repo). You can easily break videos into parts using MediaMuxer (API 18+).

If you are targetting API 15, 16, 17, or even lower APIs, you still can use MediaCodec, but instead of being done internally using the concept of surface, video will be processed by passing ByteBuffers between decoder and encoder. There is a slight drop in performance, let's say it is cut in half (30 fps), and you have to guess how your GPU chip is decoding frames. (YUV NV21, NV12, YV12, YV16) before rendering it or passing it to your encoder. (You'll start to read about YUV images specs, and you'll realize how horible is this concept of "strides".) Once you cover all the exceptions, you have a very retro-compatible engine. (\* For YUV detection format, a workaround would be a fuzzy algo to compare the result of the first primary frame using different formats (NV21, NV12, etc.) with the first frame extracted by MediaMetaDataRetriever until you get no significative differences.)

When using API < 18, use Mp4Parser Java project with bindings. (It would be nice if someone ported it to .Net.) Mp4Parser works incredibility well with H.264 / AAC.

Anyway, check all my repos. I'm covering everything with my repos, though I'm not playing with MediaMuxer, which, I guess, is very simple. There is an example in the encoding demo, though.

**Comment by beeradmoore** [comment]
Thanks a lot! This has given me a lot to think about and tinker with.

"You can't produce any mpeg stuff without paying royalties"
Can you elaborate on this or link me to any references. I thought using ffmpeg within its own licence terms was ok to do.

**Comment by leye0** [comment]
The question is interesting. Royalties to pay to MPEGLA seems to always having been a problem when it comes to use H.264. I wonder if Google pre-pays for the royalties when we buy a device. It would be strange to have to bother about royalties when using APIs that are native to the device. We can clearly read in logcat that Android OS contains FFMPEG, which is GNU GPL 2.1, almost like Android (GNU GPL 2.0). Now, is an application a "functionality" of an Android device, the latter sharing its source code, or a stand-alone product... 

Maybe we can't sell apps using H264, maybe that's ok. It worths searching about it. 

I've not started the publishing process yet for my current video processing application, so I'm not aware yet of licensing issues I'll meet.

Personnaly, one of the main reason why I've used Android APIs and raised to API 18 - losing 25% of the market - is to have some umbrella between MPEGLA patent/licenses and the app.

**Comment by beeradmoore** [comment]
Lol, yeah, I can't understand french. All good though.

I don't have a lot of issues dropping support to API 18. I tend to aim for API 15 compatibility. But considering the hard work the device will be doing I feel its safe to assume the devices used by people will be >4.3, and probably hardware on par with a Galaxy S4 or greater. As in, I don't mind not supporting the $100 phones from the supermarket which may only be on 4.0 anyway.
